# Generated by Django 3.1.4 on 2021-01-10 12:26

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=1, max_length=100, validators=[blog.validators.validate_author]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Jurnal', 'jurnal'), ('Blog', 'blog'), ('Berita', 'berita')], default='blog', max_length=100),
        ),
    ]
