# Generated by Django 3.1.4 on 2021-01-23 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210123_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'default_permissions': ('add',), 'permissions': (('can_publish', 'can publish artikel'), ('can_edit', 'can edit artikel'))},
        ),
        migrations.AddField(
            model_name='artikel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikel',
            name='is_published',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
