# Generated by Django 3.1.4 on 2021-01-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210123_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='is_published',
            field=models.BooleanField(),
        ),
    ]
