# Generated by Django 3.1.4 on 2021-01-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField()),
                ('published', models.DateTimeField(null=True)),
            ],
            options={
                'permissions': (('can_publish', 'can publish artikel'), ('can_edit', 'can edit artikel')),
                'default_permissions': ('add',),
            },
        ),
    ]
